### ISSUE TITLE
Adição de Docker no projeto

### ISSUE THREAD

**Issue by juliocesarkek** [MLRG-CEFET-RJ/pondoc#2]
**COMO** colaborador do projeto ou pessoa que vai utilizar no futuro, 

**GOSTARIA** que fosse criado um Docker para a aplicação,

**DE FORMA** que eu possa executá-la em qualquer sistema operacional de forma fácil e rápida, sem necessidade de instalações manuais das dependências.

>
**CRITÉRIOS DE ACEITAÇÃO:**
- [x] O Docker deve conter todas as dependências necessárias para a execução da aplicação.
- [x] A imagem Docker deve ser criada usando um arquivo Dock Compose.
- [x] O Docker deve ser fornecido com documentação clara e fácil de seguir para que outros usuários possam instalá-lo e executá-lo facilmente.

OBS.: Use os comentários dessa issue para documentar como rodar o docker.

**Comment by grocre** [comment]
Terminado. Aproveitei pra mexer um pouco na estrutura do projeto. Arquivos com código foram para a pasta source. Além disso, foram adicionados os arquivos requirements.txt para subir o container mais rápido e assim conseguir fazer a instalação das dependências mais rápido. Localmente estamos usando tanto o container encapsulado e também uma venv caso seja preciso realizar um teste rápido
