### ISSUE TITLE
Estruturação do banco de dados

### ISSUE THREAD

**Issue by juliocesarkek** [MLRG-CEFET-RJ/pondoc#3]
**COMO** colaborador, gostaria que fosse estruturado um banco de dados para o projeto já existente,

**DE FORMA** que eu possa armazenar e acessar facilmente os dados coletados.

**CRITÉRIOS DE ACEITAÇÃO:**
- [x] Deve ser estruturado um banco de dados SQL ou NoSQL que possa armazenar os dados coletados pelo web scraper.
 - [x] O banco de dados deve ser projetado para que possa ser facilmente consultado e atualizado com novos dados.
- [x] Deve  ser fornecida documentação clara e fácil de seguir para que pessoar no futuro saibam como acessar e trabalhar com os dados no novo modelo estruturado do banco de dados.

OBS: Utilize os comentários dessa issue para ir documentado o que foi feito em relação ao banco de dados.

**Comment by juliocesarkek** [comment]
Agora está sendo possível se conectar com o banco.

**Comment by grocre** [comment]
Coloquei os IDs lá. Já tá lançando os nomes nas tables com essa nova propriedade

**Comment by grocre** [comment]
![ERD with colored entities (UML notation)](https://github.com/MLRG-CEFET-RJ/pondoc/assets/62205909/3f0ce2a2-d3cf-4b76-8517-da74031f587f)
