### ISSUE TITLE
Baixar relatórios gerados na página inicial

### ISSUE THREAD

**Issue by juliocesarkek** [MLRG-CEFET-RJ/pondoc#9]
**COMO** usuário final do sistema, 

**GOSTARIA** que fosse possível baixar os relatórios gerados pelo sistema,
 
**PARA** realizar a análise das pontuações lattes dos professores da instituição. 

**CRITÉRIOS DE ACEITAÇÃO**
- [x] 1. Tenho que conseguir gerar relatório por período, tendo como selecionar qual período eu quero;
- [x] 2. Tem que ser possível visualizar de modo claro e objetivo a pontuação de cada docente; 
- [x] 3. Os dados fornecidos devem ser verídicos, correspondendo a realidade sem mais ou menos pontos dos que realmente existem;
- [x] 4. O formato de acesso deve para gerar os dados, enquanto usuário, deve ser feito via executável, de baixa complexidade para seu uso. Isto é, uma pessoa leiga com poucos cliques conseguindo gerar os dados que busca.

**Comment by grocre** [comment]
A Api já está realizando o download assim que os dados são baixados
